M48
; DRILL file {KiCad (6.0.6)} date Thu Aug  4 20:50:49 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-04T20:50:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.6)
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0827
%
G90
G05
T1
X5.7Y-4.05
X6.2Y-4.05
X6.7Y-4.05
X7.2Y-4.05
T2
X7.3776Y-3.9506
X7.3776Y-4.0506
X7.3776Y-4.1506
X7.4776Y-3.9506
X7.4776Y-4.0506
X7.4776Y-4.1506
T3
X5.4Y-3.85
X5.4Y-4.2
T0
M30
